CREATE TABLE `resultsToyota` (
    `vin` VARCHAR(17) CHARACTER SET utf8 NOT NULL,
    `make` VARCHAR(17) CHARACTER SET utf8,
    `year` INT,
    `dealer` VARCHAR(26) CHARACTER SET utf8,
    `dealerWebsite` VARCHAR(39) CHARACTER SET utf8,
    `advertizedPrice` INT,
    `nonSpAdvertizedPrice` INT,
    `totalMsrp` INT,
    `sellingPrice` INT,
    `dph` INT,
    `dioTotalMsrp` INT,
    `dioTotalDealerSellingPrice` INT,
    `dealerCashApplied` INT,
    `baseMsrp` INT,
    `options` VARCHAR(445) CHARACTER SET utf8,
    `model` VARCHAR(26) CHARACTER SET utf8,
    `intColor_marketingName` VARCHAR(30) CHARACTER SET utf8,
    `intColor_nvsName` VARCHAR(15) CHARACTER SET utf8,
    `intColor_colorFamilies` VARCHAR(4) CHARACTER SET utf8,
    `extColor_marketingName` VARCHAR(35) CHARACTER SET utf8,
    `extColor_nvsName` VARCHAR(23) CHARACTER SET utf8,
    `extColor_colorFamilies` VARCHAR(5) CHARACTER SET utf8,
    `addedDate` DATE DEFAULT (CURRENT_DATE),
    PRIMARY KEY (`vin`)
);
